/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module x (
  input [2:0] s,
  output o
);
  assign o = (s[0] ^ ((s[1] ^ 1'b1) & s[2]));
endmodule

module x64_61 (
  input [63:0] i_64,
  output [61:0] o_64
);
  wire [2:0] s0;
  wire [2:0] s1;
  wire [2:0] s2;
  wire [2:0] s3;
  wire [2:0] s4;
  wire [2:0] s5;
  wire [2:0] s6;
  wire [2:0] s7;
  wire [2:0] s8;
  wire [2:0] s9;
  wire [2:0] s10;
  wire [2:0] s11;
  wire [2:0] s12;
  wire [2:0] s13;
  wire [2:0] s14;
  wire [2:0] s15;
  wire [2:0] s16;
  wire [2:0] s17;
  wire [2:0] s18;
  wire [2:0] s19;
  wire [2:0] s20;
  wire [2:0] s21;
  wire [2:0] s22;
  wire [2:0] s23;
  wire [2:0] s24;
  wire [2:0] s25;
  wire [2:0] s26;
  wire [2:0] s27;
  wire [2:0] s28;
  wire [2:0] s29;
  wire [2:0] s30;
  wire [2:0] s31;
  wire [2:0] s32;
  wire [2:0] s33;
  wire [2:0] s34;
  wire [2:0] s35;
  wire [2:0] s36;
  wire [2:0] s37;
  wire [2:0] s38;
  wire [2:0] s39;
  wire [2:0] s40;
  wire [2:0] s41;
  wire [2:0] s42;
  wire [2:0] s43;
  wire [2:0] s44;
  wire [2:0] s45;
  wire [2:0] s46;
  wire [2:0] s47;
  wire [2:0] s48;
  wire [2:0] s49;
  wire [2:0] s50;
  wire [2:0] s51;
  wire [2:0] s52;
  wire [2:0] s53;
  wire [2:0] s54;
  wire [2:0] s55;
  wire [2:0] s56;
  wire [2:0] s57;
  wire [2:0] s58;
  wire [2:0] s59;
  wire [2:0] s60;
  wire [2:0] s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire s66;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire s82;
  wire s83;
  wire s84;
  wire s85;
  wire s86;
  wire s87;
  wire s88;
  wire s89;
  wire s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  wire s95;
  wire s96;
  wire s97;
  wire s98;
  wire s99;
  wire s100;
  wire s101;
  wire s102;
  wire s103;
  wire s104;
  wire s105;
  wire s106;
  wire s107;
  wire s108;
  wire s109;
  wire s110;
  wire s111;
  wire s112;
  wire s113;
  wire s114;
  wire s115;
  wire s116;
  wire s117;
  wire s118;
  wire s119;
  wire s120;
  wire s121;
  wire s122;
  wire s123;
  assign s0 = i_64[2:0];
  assign s1 = i_64[3:1];
  assign s2 = i_64[4:2];
  assign s3 = i_64[5:3];
  assign s4 = i_64[6:4];
  assign s5 = i_64[7:5];
  assign s6 = i_64[8:6];
  assign s7 = i_64[9:7];
  assign s8 = i_64[10:8];
  assign s9 = i_64[11:9];
  assign s10 = i_64[12:10];
  assign s11 = i_64[13:11];
  assign s12 = i_64[14:12];
  assign s13 = i_64[15:13];
  assign s14 = i_64[16:14];
  assign s15 = i_64[17:15];
  assign s16 = i_64[18:16];
  assign s17 = i_64[19:17];
  assign s18 = i_64[20:18];
  assign s19 = i_64[21:19];
  assign s20 = i_64[22:20];
  assign s21 = i_64[23:21];
  assign s22 = i_64[24:22];
  assign s23 = i_64[25:23];
  assign s24 = i_64[26:24];
  assign s25 = i_64[27:25];
  assign s26 = i_64[28:26];
  assign s27 = i_64[29:27];
  assign s28 = i_64[30:28];
  assign s29 = i_64[31:29];
  assign s30 = i_64[32:30];
  assign s31 = i_64[33:31];
  assign s32 = i_64[34:32];
  assign s33 = i_64[35:33];
  assign s34 = i_64[36:34];
  assign s35 = i_64[37:35];
  assign s36 = i_64[38:36];
  assign s37 = i_64[39:37];
  assign s38 = i_64[40:38];
  assign s39 = i_64[41:39];
  assign s40 = i_64[42:40];
  assign s41 = i_64[43:41];
  assign s42 = i_64[44:42];
  assign s43 = i_64[45:43];
  assign s44 = i_64[46:44];
  assign s45 = i_64[47:45];
  assign s46 = i_64[48:46];
  assign s47 = i_64[49:47];
  assign s48 = i_64[50:48];
  assign s49 = i_64[51:49];
  assign s50 = i_64[52:50];
  assign s51 = i_64[53:51];
  assign s52 = i_64[54:52];
  assign s53 = i_64[55:53];
  assign s54 = i_64[56:54];
  assign s55 = i_64[57:55];
  assign s56 = i_64[58:56];
  assign s57 = i_64[59:57];
  assign s58 = i_64[60:58];
  assign s59 = i_64[61:59];
  assign s60 = i_64[62:60];
  assign s61 = i_64[63:61];
  x x_i0 (
    .s( s0 ),
    .o( s62 )
  );
  x x_i1 (
    .s( s1 ),
    .o( s63 )
  );
  x x_i2 (
    .s( s2 ),
    .o( s64 )
  );
  x x_i3 (
    .s( s3 ),
    .o( s65 )
  );
  x x_i4 (
    .s( s4 ),
    .o( s66 )
  );
  x x_i5 (
    .s( s5 ),
    .o( s67 )
  );
  x x_i6 (
    .s( s6 ),
    .o( s68 )
  );
  x x_i7 (
    .s( s7 ),
    .o( s69 )
  );
  x x_i8 (
    .s( s8 ),
    .o( s70 )
  );
  x x_i9 (
    .s( s9 ),
    .o( s71 )
  );
  x x_i10 (
    .s( s10 ),
    .o( s72 )
  );
  x x_i11 (
    .s( s11 ),
    .o( s73 )
  );
  x x_i12 (
    .s( s12 ),
    .o( s74 )
  );
  x x_i13 (
    .s( s13 ),
    .o( s75 )
  );
  x x_i14 (
    .s( s14 ),
    .o( s76 )
  );
  x x_i15 (
    .s( s15 ),
    .o( s77 )
  );
  x x_i16 (
    .s( s16 ),
    .o( s78 )
  );
  x x_i17 (
    .s( s17 ),
    .o( s79 )
  );
  x x_i18 (
    .s( s18 ),
    .o( s80 )
  );
  x x_i19 (
    .s( s19 ),
    .o( s81 )
  );
  x x_i20 (
    .s( s20 ),
    .o( s82 )
  );
  x x_i21 (
    .s( s21 ),
    .o( s83 )
  );
  x x_i22 (
    .s( s22 ),
    .o( s84 )
  );
  x x_i23 (
    .s( s23 ),
    .o( s85 )
  );
  x x_i24 (
    .s( s24 ),
    .o( s86 )
  );
  x x_i25 (
    .s( s25 ),
    .o( s87 )
  );
  x x_i26 (
    .s( s26 ),
    .o( s88 )
  );
  x x_i27 (
    .s( s27 ),
    .o( s89 )
  );
  x x_i28 (
    .s( s28 ),
    .o( s90 )
  );
  x x_i29 (
    .s( s29 ),
    .o( s91 )
  );
  x x_i30 (
    .s( s30 ),
    .o( s92 )
  );
  x x_i31 (
    .s( s31 ),
    .o( s93 )
  );
  x x_i32 (
    .s( s32 ),
    .o( s94 )
  );
  x x_i33 (
    .s( s33 ),
    .o( s95 )
  );
  x x_i34 (
    .s( s34 ),
    .o( s96 )
  );
  x x_i35 (
    .s( s35 ),
    .o( s97 )
  );
  x x_i36 (
    .s( s36 ),
    .o( s98 )
  );
  x x_i37 (
    .s( s37 ),
    .o( s99 )
  );
  x x_i38 (
    .s( s38 ),
    .o( s100 )
  );
  x x_i39 (
    .s( s39 ),
    .o( s101 )
  );
  x x_i40 (
    .s( s40 ),
    .o( s102 )
  );
  x x_i41 (
    .s( s41 ),
    .o( s103 )
  );
  x x_i42 (
    .s( s42 ),
    .o( s104 )
  );
  x x_i43 (
    .s( s43 ),
    .o( s105 )
  );
  x x_i44 (
    .s( s44 ),
    .o( s106 )
  );
  x x_i45 (
    .s( s45 ),
    .o( s107 )
  );
  x x_i46 (
    .s( s46 ),
    .o( s108 )
  );
  x x_i47 (
    .s( s47 ),
    .o( s109 )
  );
  x x_i48 (
    .s( s48 ),
    .o( s110 )
  );
  x x_i49 (
    .s( s49 ),
    .o( s111 )
  );
  x x_i50 (
    .s( s50 ),
    .o( s112 )
  );
  x x_i51 (
    .s( s51 ),
    .o( s113 )
  );
  x x_i52 (
    .s( s52 ),
    .o( s114 )
  );
  x x_i53 (
    .s( s53 ),
    .o( s115 )
  );
  x x_i54 (
    .s( s54 ),
    .o( s116 )
  );
  x x_i55 (
    .s( s55 ),
    .o( s117 )
  );
  x x_i56 (
    .s( s56 ),
    .o( s118 )
  );
  x x_i57 (
    .s( s57 ),
    .o( s119 )
  );
  x x_i58 (
    .s( s58 ),
    .o( s120 )
  );
  x x_i59 (
    .s( s59 ),
    .o( s121 )
  );
  x x_i60 (
    .s( s60 ),
    .o( s122 )
  );
  x x_i61 (
    .s( s61 ),
    .o( s123 )
  );
  assign o_64[0] = s62;
  assign o_64[1] = s63;
  assign o_64[2] = s64;
  assign o_64[3] = s65;
  assign o_64[4] = s66;
  assign o_64[5] = s67;
  assign o_64[6] = s68;
  assign o_64[7] = s69;
  assign o_64[8] = s70;
  assign o_64[9] = s71;
  assign o_64[10] = s72;
  assign o_64[11] = s73;
  assign o_64[12] = s74;
  assign o_64[13] = s75;
  assign o_64[14] = s76;
  assign o_64[15] = s77;
  assign o_64[16] = s78;
  assign o_64[17] = s79;
  assign o_64[18] = s80;
  assign o_64[19] = s81;
  assign o_64[20] = s82;
  assign o_64[21] = s83;
  assign o_64[22] = s84;
  assign o_64[23] = s85;
  assign o_64[24] = s86;
  assign o_64[25] = s87;
  assign o_64[26] = s88;
  assign o_64[27] = s89;
  assign o_64[28] = s90;
  assign o_64[29] = s91;
  assign o_64[30] = s92;
  assign o_64[31] = s93;
  assign o_64[32] = s94;
  assign o_64[33] = s95;
  assign o_64[34] = s96;
  assign o_64[35] = s97;
  assign o_64[36] = s98;
  assign o_64[37] = s99;
  assign o_64[38] = s100;
  assign o_64[39] = s101;
  assign o_64[40] = s102;
  assign o_64[41] = s103;
  assign o_64[42] = s104;
  assign o_64[43] = s105;
  assign o_64[44] = s106;
  assign o_64[45] = s107;
  assign o_64[46] = s108;
  assign o_64[47] = s109;
  assign o_64[48] = s110;
  assign o_64[49] = s111;
  assign o_64[50] = s112;
  assign o_64[51] = s113;
  assign o_64[52] = s114;
  assign o_64[53] = s115;
  assign o_64[54] = s116;
  assign o_64[55] = s117;
  assign o_64[56] = s118;
  assign o_64[57] = s119;
  assign o_64[58] = s120;
  assign o_64[59] = s121;
  assign o_64[60] = s122;
  assign o_64[61] = s123;
endmodule

// ? : s_i ? s_i + (s_i+1 + 1)s_i+2 ,
module \?  (
  input [63:0] \64-127 ,
  input [63:0] \128-191 ,
  input [63:0] \191-255 ,
  input [63:0] \0-63 ,
  input \256 ,
  output [63:0] \o0-63 ,
  output [63:0] \o64-127 ,
  output [63:0] \o128-191 ,
  output [63:0] \o192-255 ,
  output o256
);
  wire [63:0] s0;
  wire [61:0] s1;
  wire s2;
  wire [63:0] s3;
  wire s4;
  wire [2:0] s5;
  wire s6;
  wire [2:0] s7;
  wire s8;
  wire s9;
  wire [61:0] s10;
  wire [2:0] s11;
  wire s12;
  wire [2:0] s13;
  wire s14;
  wire s15;
  wire [63:0] s16;
  wire s17;
  wire [61:0] s18;
  wire [2:0] s19;
  wire s20;
  wire [2:0] s21;
  wire s22;
  wire s23;
  wire [63:0] s24;
  wire s25;
  wire s26;
  wire [61:0] s27;
  wire [2:0] s28;
  wire s29;
  wire [2:0] s30;
  wire s31;
  wire [2:0] s32;
  assign s2 = \64-127 [0];
  assign s3 = \64-127 [63:0];
  assign s4 = \64-127 [63];
  assign s15 = \128-191 [0];
  assign s16 = \128-191 [63:0];
  assign s17 = \128-191 [63];
  assign s23 = \191-255 [0];
  assign s24 = \191-255 [63:0];
  assign s25 = \191-255 [63];
  assign s26 = \0-63 [0];
  assign s0 = \0-63 [63:0];
  assign s9 = \0-63 [63];
  x64_61 x64_61_i0 (
    .i_64( s0 ),
    .o_64( s1 )
  );
  assign s5[0] = \0-63 [62];
  assign s5[1] = s9;
  assign s5[2] = s2;
  assign s7[0] = s9;
  assign s7[1] = s2;
  assign s7[2] = \64-127 [1];
  x64_61 x64_61_i1 (
    .i_64( s3 ),
    .o_64( s10 )
  );
  assign s11[0] = \64-127 [62];
  assign s11[1] = s4;
  assign s11[2] = s15;
  assign s13[0] = s4;
  assign s13[1] = s15;
  assign s13[2] = \128-191 [1];
  x64_61 x64_61_i2 (
    .i_64( s16 ),
    .o_64( s18 )
  );
  assign s19[0] = \128-191 [62];
  assign s19[1] = s17;
  assign s19[2] = s23;
  assign s21[0] = s17;
  assign s21[1] = s23;
  assign s21[2] = \191-255 [1];
  x64_61 x64_61_i3 (
    .i_64( s24 ),
    .o_64( s27 )
  );
  assign s28[0] = \191-255 [62];
  assign s28[1] = s25;
  assign s28[2] = \256 ;
  assign s30[0] = s25;
  assign s30[1] = \256 ;
  assign s30[2] = s26;
  assign s32[0] = \256 ;
  assign s32[1] = s26;
  assign s32[2] = \0-63 [1];
  x x_i4 (
    .s( s5 ),
    .o( s6 )
  );
  x x_i5 (
    .s( s7 ),
    .o( s8 )
  );
  x x_i6 (
    .s( s11 ),
    .o( s12 )
  );
  x x_i7 (
    .s( s13 ),
    .o( s14 )
  );
  x x_i8 (
    .s( s19 ),
    .o( s20 )
  );
  x x_i9 (
    .s( s21 ),
    .o( s22 )
  );
  x x_i10 (
    .s( s28 ),
    .o( s29 )
  );
  x x_i11 (
    .s( s30 ),
    .o( s31 )
  );
  x x_i12 (
    .s( s32 ),
    .o( o256 )
  );
  assign \o0-63 [61:0] = s1;
  assign \o0-63 [62] = s6;
  assign \o0-63 [63] = s8;
  assign \o64-127 [61:0] = s10;
  assign \o64-127 [62] = s12;
  assign \o64-127 [63] = s14;
  assign \o128-191 [61:0] = s18;
  assign \o128-191 [62] = s20;
  assign \o128-191 [63] = s22;
  assign \o192-255 [61:0] = s27;
  assign \o192-255 [62] = s29;
  assign \o192-255 [63] = s31;
endmodule

// ? : si ? si + ?i
// where ?_i = 1 if i = 0 else 1
module \?  (
  input [63:0] \64-127 ,
  input [63:0] \128-191 ,
  input [63:0] \191-255 ,
  input [63:0] \0-63 ,
  input \256 ,
  output [63:0] \o0-63 ,
  output [63:0] \o64-127 ,
  output [63:0] \o128-191 ,
  output [63:0] \o192-255 ,
  output o256
);
  assign \o0-63 [0] = (\0-63 [0] ^ 1'b1);
  assign \o0-63 [63:1] = \0-63 [63:1];
  assign \o64-127  = \64-127 ;
  assign \o128-191  = \128-191 ;
  assign \o192-255  = \191-255 ;
  assign o256 = \256 ;
endmodule

// ? : s_i ? s_i + s_i+3 + s_i+8 ,
module \?  (
  input [63:0] \0-63 ,
  input [63:0] \64-127 ,
  input [63:0] \128-191 ,
  input [63:0] \192-255 ,
  input \256 ,
  output [63:0] \o0-63 ,
  output [63:0] \o64-127 ,
  output [63:0] \o128-191 ,
  output [63:0] \o192-255 ,
  output o256
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire s54;
  wire s55;
  wire s56;
  wire s57;
  wire s58;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire s66;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire s82;
  wire s83;
  wire s84;
  wire s85;
  wire s86;
  wire s87;
  wire s88;
  wire s89;
  wire s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  wire s95;
  wire s96;
  wire s97;
  wire s98;
  wire s99;
  wire s100;
  wire s101;
  wire s102;
  wire s103;
  wire s104;
  wire s105;
  wire s106;
  wire s107;
  wire s108;
  wire s109;
  wire s110;
  wire s111;
  wire s112;
  wire s113;
  wire s114;
  wire s115;
  wire s116;
  wire s117;
  wire s118;
  wire s119;
  wire s120;
  wire s121;
  wire s122;
  wire s123;
  wire s124;
  wire s125;
  wire s126;
  wire s127;
  wire [7:0] s128;
  wire s129;
  wire s130;
  wire s131;
  wire s132;
  wire s133;
  wire s134;
  wire s135;
  wire s136;
  wire s137;
  wire s138;
  wire s139;
  wire s140;
  wire s141;
  wire s142;
  wire s143;
  wire s144;
  wire s145;
  wire s146;
  wire s147;
  wire s148;
  wire s149;
  wire s150;
  wire s151;
  wire s152;
  wire s153;
  wire s154;
  wire s155;
  wire s156;
  wire s157;
  wire s158;
  wire s159;
  wire s160;
  wire s161;
  wire s162;
  wire s163;
  wire s164;
  wire s165;
  wire s166;
  wire s167;
  wire s168;
  wire s169;
  wire s170;
  wire s171;
  wire s172;
  wire s173;
  wire s174;
  wire s175;
  wire s176;
  wire s177;
  wire s178;
  wire s179;
  wire s180;
  wire s181;
  wire s182;
  wire s183;
  wire s184;
  wire s185;
  wire s186;
  wire s187;
  wire s188;
  wire s189;
  wire s190;
  wire s191;
  wire s192;
  wire [7:0] s193;
  wire s194;
  wire s195;
  wire s196;
  wire s197;
  wire s198;
  wire s199;
  wire s200;
  wire s201;
  wire s202;
  wire s203;
  wire s204;
  wire s205;
  wire s206;
  wire s207;
  wire s208;
  wire s209;
  wire s210;
  wire s211;
  wire s212;
  wire s213;
  wire s214;
  wire s215;
  wire s216;
  wire s217;
  wire s218;
  wire s219;
  wire s220;
  wire s221;
  wire s222;
  wire s223;
  wire s224;
  wire s225;
  wire s226;
  wire s227;
  wire s228;
  wire s229;
  wire s230;
  wire s231;
  wire s232;
  wire s233;
  wire s234;
  wire s235;
  wire s236;
  wire s237;
  wire s238;
  wire s239;
  wire s240;
  wire s241;
  wire s242;
  wire s243;
  wire s244;
  wire s245;
  wire s246;
  wire s247;
  wire s248;
  wire s249;
  wire s250;
  wire s251;
  wire s252;
  wire s253;
  wire s254;
  wire s255;
  wire s256;
  wire s257;
  wire [7:0] s258;
  assign s0 = \0-63 [0];
  assign s1 = \0-63 [1];
  assign s2 = \0-63 [2];
  assign s3 = \0-63 [3];
  assign s4 = \0-63 [4];
  assign s5 = \0-63 [5];
  assign s6 = \0-63 [6];
  assign s7 = \0-63 [7];
  assign s8 = \0-63 [8];
  assign s9 = \0-63 [9];
  assign s10 = \0-63 [10];
  assign s11 = \0-63 [11];
  assign s12 = \0-63 [12];
  assign s13 = \0-63 [13];
  assign s14 = \0-63 [14];
  assign s15 = \0-63 [15];
  assign s16 = \0-63 [16];
  assign s17 = \0-63 [17];
  assign s18 = \0-63 [18];
  assign s19 = \0-63 [19];
  assign s20 = \0-63 [20];
  assign s21 = \0-63 [21];
  assign s22 = \0-63 [22];
  assign s23 = \0-63 [23];
  assign s24 = \0-63 [24];
  assign s25 = \0-63 [25];
  assign s26 = \0-63 [26];
  assign s27 = \0-63 [27];
  assign s28 = \0-63 [28];
  assign s29 = \0-63 [29];
  assign s30 = \0-63 [30];
  assign s31 = \0-63 [31];
  assign s32 = \0-63 [32];
  assign s33 = \0-63 [33];
  assign s34 = \0-63 [34];
  assign s35 = \0-63 [35];
  assign s36 = \0-63 [36];
  assign s37 = \0-63 [37];
  assign s38 = \0-63 [38];
  assign s39 = \0-63 [39];
  assign s40 = \0-63 [40];
  assign s41 = \0-63 [41];
  assign s42 = \0-63 [42];
  assign s43 = \0-63 [43];
  assign s44 = \0-63 [44];
  assign s45 = \0-63 [45];
  assign s46 = \0-63 [46];
  assign s47 = \0-63 [47];
  assign s48 = \0-63 [48];
  assign s49 = \0-63 [49];
  assign s50 = \0-63 [50];
  assign s51 = \0-63 [51];
  assign s52 = \0-63 [52];
  assign s53 = \0-63 [53];
  assign s54 = \0-63 [54];
  assign s55 = \0-63 [55];
  assign s56 = \0-63 [56];
  assign s57 = \0-63 [57];
  assign s58 = \0-63 [58];
  assign s59 = \0-63 [59];
  assign s60 = \0-63 [60];
  assign s61 = \0-63 [61];
  assign s62 = \0-63 [62];
  assign s63 = \0-63 [63];
  assign s67 = \64-127 [3];
  assign s68 = \64-127 [4];
  assign s69 = \64-127 [5];
  assign s70 = \64-127 [6];
  assign s71 = \64-127 [7];
  assign s72 = \64-127 [8];
  assign s73 = \64-127 [9];
  assign s74 = \64-127 [10];
  assign s75 = \64-127 [11];
  assign s76 = \64-127 [12];
  assign s77 = \64-127 [13];
  assign s78 = \64-127 [14];
  assign s79 = \64-127 [15];
  assign s80 = \64-127 [16];
  assign s81 = \64-127 [17];
  assign s82 = \64-127 [18];
  assign s83 = \64-127 [19];
  assign s84 = \64-127 [20];
  assign s85 = \64-127 [21];
  assign s86 = \64-127 [22];
  assign s87 = \64-127 [23];
  assign s88 = \64-127 [24];
  assign s89 = \64-127 [25];
  assign s90 = \64-127 [26];
  assign s91 = \64-127 [27];
  assign s92 = \64-127 [28];
  assign s93 = \64-127 [29];
  assign s94 = \64-127 [30];
  assign s95 = \64-127 [31];
  assign s96 = \64-127 [32];
  assign s97 = \64-127 [33];
  assign s98 = \64-127 [34];
  assign s99 = \64-127 [35];
  assign s100 = \64-127 [36];
  assign s101 = \64-127 [37];
  assign s102 = \64-127 [38];
  assign s103 = \64-127 [39];
  assign s104 = \64-127 [40];
  assign s105 = \64-127 [41];
  assign s106 = \64-127 [42];
  assign s107 = \64-127 [43];
  assign s108 = \64-127 [44];
  assign s109 = \64-127 [45];
  assign s110 = \64-127 [46];
  assign s111 = \64-127 [47];
  assign s112 = \64-127 [48];
  assign s113 = \64-127 [49];
  assign s114 = \64-127 [50];
  assign s115 = \64-127 [51];
  assign s116 = \64-127 [52];
  assign s117 = \64-127 [53];
  assign s118 = \64-127 [54];
  assign s119 = \64-127 [55];
  assign s120 = \64-127 [56];
  assign s121 = \64-127 [57];
  assign s122 = \64-127 [58];
  assign s123 = \64-127 [59];
  assign s124 = \64-127 [60];
  assign s125 = \64-127 [61];
  assign s126 = \64-127 [62];
  assign s127 = \64-127 [63];
  assign s128 = \64-127 [7:0];
  assign s132 = \128-191 [3];
  assign s133 = \128-191 [4];
  assign s134 = \128-191 [5];
  assign s135 = \128-191 [6];
  assign s136 = \128-191 [7];
  assign s137 = \128-191 [8];
  assign s138 = \128-191 [9];
  assign s139 = \128-191 [10];
  assign s140 = \128-191 [11];
  assign s141 = \128-191 [12];
  assign s142 = \128-191 [13];
  assign s143 = \128-191 [14];
  assign s144 = \128-191 [15];
  assign s145 = \128-191 [16];
  assign s146 = \128-191 [17];
  assign s147 = \128-191 [18];
  assign s148 = \128-191 [19];
  assign s149 = \128-191 [20];
  assign s150 = \128-191 [21];
  assign s151 = \128-191 [22];
  assign s152 = \128-191 [23];
  assign s153 = \128-191 [24];
  assign s154 = \128-191 [25];
  assign s155 = \128-191 [26];
  assign s156 = \128-191 [27];
  assign s157 = \128-191 [28];
  assign s158 = \128-191 [29];
  assign s159 = \128-191 [30];
  assign s160 = \128-191 [31];
  assign s161 = \128-191 [32];
  assign s162 = \128-191 [33];
  assign s163 = \128-191 [34];
  assign s164 = \128-191 [35];
  assign s165 = \128-191 [36];
  assign s166 = \128-191 [37];
  assign s167 = \128-191 [38];
  assign s168 = \128-191 [39];
  assign s169 = \128-191 [40];
  assign s170 = \128-191 [41];
  assign s171 = \128-191 [42];
  assign s172 = \128-191 [43];
  assign s173 = \128-191 [44];
  assign s174 = \128-191 [45];
  assign s175 = \128-191 [46];
  assign s176 = \128-191 [47];
  assign s177 = \128-191 [48];
  assign s178 = \128-191 [49];
  assign s179 = \128-191 [50];
  assign s180 = \128-191 [51];
  assign s181 = \128-191 [52];
  assign s182 = \128-191 [53];
  assign s183 = \128-191 [54];
  assign s184 = \128-191 [55];
  assign s185 = \128-191 [56];
  assign s186 = \128-191 [57];
  assign s187 = \128-191 [58];
  assign s188 = \128-191 [59];
  assign s189 = \128-191 [60];
  assign s190 = \128-191 [61];
  assign s191 = \128-191 [62];
  assign s192 = \128-191 [63];
  assign s193 = \128-191 [7:0];
  assign s197 = \192-255 [3];
  assign s198 = \192-255 [4];
  assign s199 = \192-255 [5];
  assign s200 = \192-255 [6];
  assign s201 = \192-255 [7];
  assign s202 = \192-255 [8];
  assign s203 = \192-255 [9];
  assign s204 = \192-255 [10];
  assign s205 = \192-255 [11];
  assign s206 = \192-255 [12];
  assign s207 = \192-255 [13];
  assign s208 = \192-255 [14];
  assign s209 = \192-255 [15];
  assign s210 = \192-255 [16];
  assign s211 = \192-255 [17];
  assign s212 = \192-255 [18];
  assign s213 = \192-255 [19];
  assign s214 = \192-255 [20];
  assign s215 = \192-255 [21];
  assign s216 = \192-255 [22];
  assign s217 = \192-255 [23];
  assign s218 = \192-255 [24];
  assign s219 = \192-255 [25];
  assign s220 = \192-255 [26];
  assign s221 = \192-255 [27];
  assign s222 = \192-255 [28];
  assign s223 = \192-255 [29];
  assign s224 = \192-255 [30];
  assign s225 = \192-255 [31];
  assign s226 = \192-255 [32];
  assign s227 = \192-255 [33];
  assign s228 = \192-255 [34];
  assign s229 = \192-255 [35];
  assign s230 = \192-255 [36];
  assign s231 = \192-255 [37];
  assign s232 = \192-255 [38];
  assign s233 = \192-255 [39];
  assign s234 = \192-255 [40];
  assign s235 = \192-255 [41];
  assign s236 = \192-255 [42];
  assign s237 = \192-255 [43];
  assign s238 = \192-255 [44];
  assign s239 = \192-255 [45];
  assign s240 = \192-255 [46];
  assign s241 = \192-255 [47];
  assign s242 = \192-255 [48];
  assign s243 = \192-255 [49];
  assign s244 = \192-255 [50];
  assign s245 = \192-255 [51];
  assign s246 = \192-255 [52];
  assign s247 = \192-255 [53];
  assign s248 = \192-255 [54];
  assign s249 = \192-255 [55];
  assign s250 = \192-255 [56];
  assign s251 = \192-255 [57];
  assign s252 = \192-255 [58];
  assign s253 = \192-255 [59];
  assign s254 = \192-255 [60];
  assign s255 = \192-255 [61];
  assign s256 = \192-255 [62];
  assign s257 = \192-255 [63];
  assign s258 = \192-255 [7:0];
  assign \o192-255 [0] = (\192-255 [0] ^ s197 ^ s202);
  assign \o192-255 [1] = (\192-255 [1] ^ s198 ^ s203);
  assign \o192-255 [2] = (\192-255 [2] ^ s199 ^ s204);
  assign \o192-255 [3] = (s197 ^ s200 ^ s205);
  assign \o192-255 [4] = (s198 ^ s201 ^ s206);
  assign \o192-255 [5] = (s199 ^ s202 ^ s207);
  assign \o192-255 [6] = (s200 ^ s203 ^ s208);
  assign \o192-255 [7] = (s201 ^ s204 ^ s209);
  assign \o192-255 [8] = (s202 ^ s205 ^ s210);
  assign \o192-255 [9] = (s203 ^ s206 ^ s211);
  assign \o192-255 [10] = (s204 ^ s207 ^ s212);
  assign \o192-255 [11] = (s205 ^ s208 ^ s213);
  assign \o192-255 [12] = (s206 ^ s209 ^ s214);
  assign \o192-255 [13] = (s207 ^ s210 ^ s215);
  assign \o192-255 [14] = (s208 ^ s211 ^ s216);
  assign \o192-255 [15] = (s209 ^ s212 ^ s217);
  assign \o192-255 [16] = (s210 ^ s213 ^ s218);
  assign \o192-255 [17] = (s211 ^ s214 ^ s219);
  assign \o192-255 [18] = (s212 ^ s215 ^ s220);
  assign \o192-255 [19] = (s213 ^ s216 ^ s221);
  assign \o192-255 [20] = (s214 ^ s217 ^ s222);
  assign \o192-255 [21] = (s215 ^ s218 ^ s223);
  assign \o192-255 [22] = (s216 ^ s219 ^ s224);
  assign \o192-255 [23] = (s217 ^ s220 ^ s225);
  assign \o192-255 [24] = (s218 ^ s221 ^ s226);
  assign \o192-255 [25] = (s219 ^ s222 ^ s227);
  assign \o192-255 [26] = (s220 ^ s223 ^ s228);
  assign \o192-255 [27] = (s221 ^ s224 ^ s229);
  assign \o192-255 [28] = (s222 ^ s225 ^ s230);
  assign \o192-255 [29] = (s223 ^ s226 ^ s231);
  assign \o192-255 [30] = (s224 ^ s227 ^ s232);
  assign \o192-255 [31] = (s225 ^ s228 ^ s233);
  assign \o192-255 [32] = (s226 ^ s229 ^ s234);
  assign \o192-255 [33] = (s227 ^ s230 ^ s235);
  assign \o192-255 [34] = (s228 ^ s231 ^ s236);
  assign \o192-255 [35] = (s229 ^ s232 ^ s237);
  assign \o192-255 [36] = (s230 ^ s233 ^ s238);
  assign \o192-255 [37] = (s231 ^ s234 ^ s239);
  assign \o192-255 [38] = (s232 ^ s235 ^ s240);
  assign \o192-255 [39] = (s233 ^ s236 ^ s241);
  assign \o192-255 [40] = (s234 ^ s237 ^ s242);
  assign \o192-255 [41] = (s235 ^ s238 ^ s243);
  assign \o192-255 [42] = (s236 ^ s239 ^ s244);
  assign \o192-255 [43] = (s237 ^ s240 ^ s245);
  assign \o192-255 [44] = (s238 ^ s241 ^ s246);
  assign \o192-255 [45] = (s239 ^ s242 ^ s247);
  assign \o192-255 [46] = (s240 ^ s243 ^ s248);
  assign \o192-255 [47] = (s241 ^ s244 ^ s249);
  assign \o192-255 [48] = (s242 ^ s245 ^ s250);
  assign \o192-255 [49] = (s243 ^ s246 ^ s251);
  assign \o192-255 [50] = (s244 ^ s247 ^ s252);
  assign \o192-255 [51] = (s245 ^ s248 ^ s253);
  assign \o192-255 [52] = (s246 ^ s249 ^ s254);
  assign \o192-255 [53] = (s247 ^ s250 ^ s255);
  assign \o192-255 [54] = (s248 ^ s251 ^ s256);
  assign \o192-255 [55] = (s249 ^ s252 ^ s257);
  assign \o192-255 [56] = (s250 ^ s253 ^ \256 );
  assign \o192-255 [57] = (s251 ^ s254 ^ s0);
  assign \o192-255 [58] = (s252 ^ s255 ^ s1);
  assign \o192-255 [59] = (s253 ^ s256 ^ s2);
  assign \o192-255 [60] = (s254 ^ s257 ^ s3);
  assign \o192-255 [61] = (s255 ^ \256  ^ s4);
  assign \o192-255 [62] = (s256 ^ s0 ^ s5);
  assign \o192-255 [63] = (s257 ^ s1 ^ s6);
  assign o256 = (\256  ^ s2 ^ s7);
  assign s64 = s128[0];
  assign s65 = s128[1];
  assign s66 = s128[2];
  assign s129 = s193[0];
  assign s130 = s193[1];
  assign s131 = s193[2];
  assign s194 = s258[0];
  assign s195 = s258[1];
  assign s196 = s258[2];
  assign \o0-63 [0] = (s0 ^ s3 ^ s8);
  assign \o0-63 [1] = (s1 ^ s4 ^ s9);
  assign \o0-63 [2] = (s2 ^ s5 ^ s10);
  assign \o0-63 [3] = (s3 ^ s6 ^ s11);
  assign \o0-63 [4] = (s4 ^ s7 ^ s12);
  assign \o0-63 [5] = (s5 ^ s8 ^ s13);
  assign \o0-63 [6] = (s6 ^ s9 ^ s14);
  assign \o0-63 [7] = (s7 ^ s10 ^ s15);
  assign \o0-63 [8] = (s8 ^ s11 ^ s16);
  assign \o0-63 [9] = (s9 ^ s12 ^ s17);
  assign \o0-63 [10] = (s10 ^ s13 ^ s18);
  assign \o0-63 [11] = (s11 ^ s14 ^ s19);
  assign \o0-63 [12] = (s12 ^ s15 ^ s20);
  assign \o0-63 [13] = (s13 ^ s16 ^ s21);
  assign \o0-63 [14] = (s14 ^ s17 ^ s22);
  assign \o0-63 [15] = (s15 ^ s18 ^ s23);
  assign \o0-63 [16] = (s16 ^ s19 ^ s24);
  assign \o0-63 [17] = (s17 ^ s20 ^ s25);
  assign \o0-63 [18] = (s18 ^ s21 ^ s26);
  assign \o0-63 [19] = (s19 ^ s22 ^ s27);
  assign \o0-63 [20] = (s20 ^ s23 ^ s28);
  assign \o0-63 [21] = (s21 ^ s24 ^ s29);
  assign \o0-63 [22] = (s22 ^ s25 ^ s30);
  assign \o0-63 [23] = (s23 ^ s26 ^ s31);
  assign \o0-63 [24] = (s24 ^ s27 ^ s32);
  assign \o0-63 [25] = (s25 ^ s28 ^ s33);
  assign \o0-63 [26] = (s26 ^ s29 ^ s34);
  assign \o0-63 [27] = (s27 ^ s30 ^ s35);
  assign \o0-63 [28] = (s28 ^ s31 ^ s36);
  assign \o0-63 [29] = (s29 ^ s32 ^ s37);
  assign \o0-63 [30] = (s30 ^ s33 ^ s38);
  assign \o0-63 [31] = (s31 ^ s34 ^ s39);
  assign \o0-63 [32] = (s32 ^ s35 ^ s40);
  assign \o0-63 [33] = (s33 ^ s36 ^ s41);
  assign \o0-63 [34] = (s34 ^ s37 ^ s42);
  assign \o0-63 [35] = (s35 ^ s38 ^ s43);
  assign \o0-63 [36] = (s36 ^ s39 ^ s44);
  assign \o0-63 [37] = (s37 ^ s40 ^ s45);
  assign \o0-63 [38] = (s38 ^ s41 ^ s46);
  assign \o0-63 [39] = (s39 ^ s42 ^ s47);
  assign \o0-63 [40] = (s40 ^ s43 ^ s48);
  assign \o0-63 [41] = (s41 ^ s44 ^ s49);
  assign \o0-63 [42] = (s42 ^ s45 ^ s50);
  assign \o0-63 [43] = (s43 ^ s46 ^ s51);
  assign \o0-63 [44] = (s44 ^ s47 ^ s52);
  assign \o0-63 [45] = (s45 ^ s48 ^ s53);
  assign \o0-63 [46] = (s46 ^ s49 ^ s54);
  assign \o0-63 [47] = (s47 ^ s50 ^ s55);
  assign \o0-63 [48] = (s48 ^ s51 ^ s56);
  assign \o0-63 [49] = (s49 ^ s52 ^ s57);
  assign \o0-63 [50] = (s50 ^ s53 ^ s58);
  assign \o0-63 [51] = (s51 ^ s54 ^ s59);
  assign \o0-63 [52] = (s52 ^ s55 ^ s60);
  assign \o0-63 [53] = (s53 ^ s56 ^ s61);
  assign \o0-63 [54] = (s54 ^ s57 ^ s62);
  assign \o0-63 [55] = (s55 ^ s58 ^ s63);
  assign \o0-63 [56] = (s56 ^ s59 ^ s64);
  assign \o0-63 [57] = (s57 ^ s60 ^ s65);
  assign \o0-63 [58] = (s58 ^ s61 ^ s66);
  assign \o0-63 [59] = (s59 ^ s62 ^ s128[3]);
  assign \o0-63 [60] = (s60 ^ s63 ^ s128[4]);
  assign \o0-63 [61] = (s61 ^ s64 ^ s128[5]);
  assign \o0-63 [62] = (s62 ^ s65 ^ s128[6]);
  assign \o0-63 [63] = (s63 ^ s66 ^ s128[7]);
  assign \o64-127 [0] = (\64-127 [0] ^ s67 ^ s72);
  assign \o64-127 [1] = (\64-127 [1] ^ s68 ^ s73);
  assign \o64-127 [2] = (\64-127 [2] ^ s69 ^ s74);
  assign \o64-127 [3] = (s67 ^ s70 ^ s75);
  assign \o64-127 [4] = (s68 ^ s71 ^ s76);
  assign \o64-127 [5] = (s69 ^ s72 ^ s77);
  assign \o64-127 [6] = (s70 ^ s73 ^ s78);
  assign \o64-127 [7] = (s71 ^ s74 ^ s79);
  assign \o64-127 [8] = (s72 ^ s75 ^ s80);
  assign \o64-127 [9] = (s73 ^ s76 ^ s81);
  assign \o64-127 [10] = (s74 ^ s77 ^ s82);
  assign \o64-127 [11] = (s75 ^ s78 ^ s83);
  assign \o64-127 [12] = (s76 ^ s79 ^ s84);
  assign \o64-127 [13] = (s77 ^ s80 ^ s85);
  assign \o64-127 [14] = (s78 ^ s81 ^ s86);
  assign \o64-127 [15] = (s79 ^ s82 ^ s87);
  assign \o64-127 [16] = (s80 ^ s83 ^ s88);
  assign \o64-127 [17] = (s81 ^ s84 ^ s89);
  assign \o64-127 [18] = (s82 ^ s85 ^ s90);
  assign \o64-127 [19] = (s83 ^ s86 ^ s91);
  assign \o64-127 [20] = (s84 ^ s87 ^ s92);
  assign \o64-127 [21] = (s85 ^ s88 ^ s93);
  assign \o64-127 [22] = (s86 ^ s89 ^ s94);
  assign \o64-127 [23] = (s87 ^ s90 ^ s95);
  assign \o64-127 [24] = (s88 ^ s91 ^ s96);
  assign \o64-127 [25] = (s89 ^ s92 ^ s97);
  assign \o64-127 [26] = (s90 ^ s93 ^ s98);
  assign \o64-127 [27] = (s91 ^ s94 ^ s99);
  assign \o64-127 [28] = (s92 ^ s95 ^ s100);
  assign \o64-127 [29] = (s93 ^ s96 ^ s101);
  assign \o64-127 [30] = (s94 ^ s97 ^ s102);
  assign \o64-127 [31] = (s95 ^ s98 ^ s103);
  assign \o64-127 [32] = (s96 ^ s99 ^ s104);
  assign \o64-127 [33] = (s97 ^ s100 ^ s105);
  assign \o64-127 [34] = (s98 ^ s101 ^ s106);
  assign \o64-127 [35] = (s99 ^ s102 ^ s107);
  assign \o64-127 [36] = (s100 ^ s103 ^ s108);
  assign \o64-127 [37] = (s101 ^ s104 ^ s109);
  assign \o64-127 [38] = (s102 ^ s105 ^ s110);
  assign \o64-127 [39] = (s103 ^ s106 ^ s111);
  assign \o64-127 [40] = (s104 ^ s107 ^ s112);
  assign \o64-127 [41] = (s105 ^ s108 ^ s113);
  assign \o64-127 [42] = (s106 ^ s109 ^ s114);
  assign \o64-127 [43] = (s107 ^ s110 ^ s115);
  assign \o64-127 [44] = (s108 ^ s111 ^ s116);
  assign \o64-127 [45] = (s109 ^ s112 ^ s117);
  assign \o64-127 [46] = (s110 ^ s113 ^ s118);
  assign \o64-127 [47] = (s111 ^ s114 ^ s119);
  assign \o64-127 [48] = (s112 ^ s115 ^ s120);
  assign \o64-127 [49] = (s113 ^ s116 ^ s121);
  assign \o64-127 [50] = (s114 ^ s117 ^ s122);
  assign \o64-127 [51] = (s115 ^ s118 ^ s123);
  assign \o64-127 [52] = (s116 ^ s119 ^ s124);
  assign \o64-127 [53] = (s117 ^ s120 ^ s125);
  assign \o64-127 [54] = (s118 ^ s121 ^ s126);
  assign \o64-127 [55] = (s119 ^ s122 ^ s127);
  assign \o64-127 [56] = (s120 ^ s123 ^ s129);
  assign \o64-127 [57] = (s121 ^ s124 ^ s130);
  assign \o64-127 [58] = (s122 ^ s125 ^ s131);
  assign \o64-127 [59] = (s123 ^ s126 ^ s193[3]);
  assign \o64-127 [60] = (s124 ^ s127 ^ s193[4]);
  assign \o64-127 [61] = (s125 ^ s129 ^ s193[5]);
  assign \o64-127 [62] = (s126 ^ s130 ^ s193[6]);
  assign \o64-127 [63] = (s127 ^ s131 ^ s193[7]);
  assign \o128-191 [0] = (\128-191 [0] ^ s132 ^ s137);
  assign \o128-191 [1] = (\128-191 [1] ^ s133 ^ s138);
  assign \o128-191 [2] = (\128-191 [2] ^ s134 ^ s139);
  assign \o128-191 [3] = (s132 ^ s135 ^ s140);
  assign \o128-191 [4] = (s133 ^ s136 ^ s141);
  assign \o128-191 [5] = (s134 ^ s137 ^ s142);
  assign \o128-191 [6] = (s135 ^ s138 ^ s143);
  assign \o128-191 [7] = (s136 ^ s139 ^ s144);
  assign \o128-191 [8] = (s137 ^ s140 ^ s145);
  assign \o128-191 [9] = (s138 ^ s141 ^ s146);
  assign \o128-191 [10] = (s139 ^ s142 ^ s147);
  assign \o128-191 [11] = (s140 ^ s143 ^ s148);
  assign \o128-191 [12] = (s141 ^ s144 ^ s149);
  assign \o128-191 [13] = (s142 ^ s145 ^ s150);
  assign \o128-191 [14] = (s143 ^ s146 ^ s151);
  assign \o128-191 [15] = (s144 ^ s147 ^ s152);
  assign \o128-191 [16] = (s145 ^ s148 ^ s153);
  assign \o128-191 [17] = (s146 ^ s149 ^ s154);
  assign \o128-191 [18] = (s147 ^ s150 ^ s155);
  assign \o128-191 [19] = (s148 ^ s151 ^ s156);
  assign \o128-191 [20] = (s149 ^ s152 ^ s157);
  assign \o128-191 [21] = (s150 ^ s153 ^ s158);
  assign \o128-191 [22] = (s151 ^ s154 ^ s159);
  assign \o128-191 [23] = (s152 ^ s155 ^ s160);
  assign \o128-191 [24] = (s153 ^ s156 ^ s161);
  assign \o128-191 [25] = (s154 ^ s157 ^ s162);
  assign \o128-191 [26] = (s155 ^ s158 ^ s163);
  assign \o128-191 [27] = (s156 ^ s159 ^ s164);
  assign \o128-191 [28] = (s157 ^ s160 ^ s165);
  assign \o128-191 [29] = (s158 ^ s161 ^ s166);
  assign \o128-191 [30] = (s159 ^ s162 ^ s167);
  assign \o128-191 [31] = (s160 ^ s163 ^ s168);
  assign \o128-191 [32] = (s161 ^ s164 ^ s169);
  assign \o128-191 [33] = (s162 ^ s165 ^ s170);
  assign \o128-191 [34] = (s163 ^ s166 ^ s171);
  assign \o128-191 [35] = (s164 ^ s167 ^ s172);
  assign \o128-191 [36] = (s165 ^ s168 ^ s173);
  assign \o128-191 [37] = (s166 ^ s169 ^ s174);
  assign \o128-191 [38] = (s167 ^ s170 ^ s175);
  assign \o128-191 [39] = (s168 ^ s171 ^ s176);
  assign \o128-191 [40] = (s169 ^ s172 ^ s177);
  assign \o128-191 [41] = (s170 ^ s173 ^ s178);
  assign \o128-191 [42] = (s171 ^ s174 ^ s179);
  assign \o128-191 [43] = (s172 ^ s175 ^ s180);
  assign \o128-191 [44] = (s173 ^ s176 ^ s181);
  assign \o128-191 [45] = (s174 ^ s177 ^ s182);
  assign \o128-191 [46] = (s175 ^ s178 ^ s183);
  assign \o128-191 [47] = (s176 ^ s179 ^ s184);
  assign \o128-191 [48] = (s177 ^ s180 ^ s185);
  assign \o128-191 [49] = (s178 ^ s181 ^ s186);
  assign \o128-191 [50] = (s179 ^ s182 ^ s187);
  assign \o128-191 [51] = (s180 ^ s183 ^ s188);
  assign \o128-191 [52] = (s181 ^ s184 ^ s189);
  assign \o128-191 [53] = (s182 ^ s185 ^ s190);
  assign \o128-191 [54] = (s183 ^ s186 ^ s191);
  assign \o128-191 [55] = (s184 ^ s187 ^ s192);
  assign \o128-191 [56] = (s185 ^ s188 ^ s194);
  assign \o128-191 [57] = (s186 ^ s189 ^ s195);
  assign \o128-191 [58] = (s187 ^ s190 ^ s196);
  assign \o128-191 [59] = (s188 ^ s191 ^ s258[3]);
  assign \o128-191 [60] = (s189 ^ s192 ^ s258[4]);
  assign \o128-191 [61] = (s190 ^ s194 ^ s258[5]);
  assign \o128-191 [62] = (s191 ^ s195 ^ s258[6]);
  assign \o128-191 [63] = (s192 ^ s196 ^ s258[7]);
endmodule

// ? : s_i ? s_12i
module \?  (
  input [63:0] \64-127 ,
  input [63:0] \128-191 ,
  input [63:0] \191-255 ,
  input [63:0] \0-63 ,
  input \256 ,
  output [63:0] \o0-63 ,
  output [63:0] \o64-127 ,
  output [63:0] \o128-191 ,
  output [63:0] \o192-255 ,
  output o256
);
  assign \o0-63 [0] = \0-63 [0];
  assign \o0-63 [1] = \0-63 [12];
  assign \o0-63 [2] = \0-63 [24];
  assign \o0-63 [3] = \0-63 [36];
  assign \o0-63 [4] = \0-63 [48];
  assign \o0-63 [5] = \0-63 [60];
  assign \o0-63 [6] = \64-127 [8];
  assign \o0-63 [7] = \64-127 [20];
  assign \o0-63 [8] = \64-127 [32];
  assign \o0-63 [9] = \64-127 [44];
  assign \o0-63 [10] = \64-127 [56];
  assign \o0-63 [11] = \128-191 [4];
  assign \o0-63 [12] = \128-191 [16];
  assign \o0-63 [13] = \128-191 [28];
  assign \o0-63 [14] = \128-191 [40];
  assign \o0-63 [15] = \128-191 [52];
  assign \o0-63 [16] = \191-255 [0];
  assign \o0-63 [17] = \191-255 [12];
  assign \o0-63 [18] = \191-255 [24];
  assign \o0-63 [19] = \191-255 [36];
  assign \o0-63 [20] = \191-255 [48];
  assign \o0-63 [21] = \191-255 [60];
  assign \o0-63 [22] = \0-63 [7];
  assign \o0-63 [23] = \0-63 [19];
  assign \o0-63 [24] = \0-63 [31];
  assign \o0-63 [25] = \0-63 [43];
  assign \o0-63 [26] = \0-63 [55];
  assign \o0-63 [27] = \64-127 [3];
  assign \o0-63 [28] = \64-127 [15];
  assign \o0-63 [29] = \64-127 [27];
  assign \o0-63 [30] = \64-127 [39];
  assign \o0-63 [31] = \64-127 [51];
  assign \o0-63 [32] = \64-127 [63];
  assign \o0-63 [33] = \128-191 [11];
  assign \o0-63 [34] = \128-191 [23];
  assign \o0-63 [35] = \128-191 [35];
  assign \o0-63 [36] = \128-191 [47];
  assign \o0-63 [37] = \128-191 [59];
  assign \o0-63 [38] = \191-255 [7];
  assign \o0-63 [39] = \191-255 [19];
  assign \o0-63 [40] = \191-255 [31];
  assign \o0-63 [41] = \191-255 [43];
  assign \o0-63 [42] = \191-255 [55];
  assign \o0-63 [43] = \0-63 [2];
  assign \o0-63 [44] = \0-63 [14];
  assign \o0-63 [45] = \0-63 [26];
  assign \o0-63 [46] = \0-63 [38];
  assign \o0-63 [47] = \0-63 [50];
  assign \o0-63 [48] = \0-63 [62];
  assign \o0-63 [49] = \64-127 [10];
  assign \o0-63 [50] = \64-127 [22];
  assign \o0-63 [51] = \64-127 [34];
  assign \o0-63 [52] = \64-127 [46];
  assign \o0-63 [53] = \64-127 [58];
  assign \o0-63 [54] = \128-191 [6];
  assign \o0-63 [55] = \128-191 [18];
  assign \o0-63 [56] = \128-191 [30];
  assign \o0-63 [57] = \128-191 [42];
  assign \o0-63 [58] = \128-191 [54];
  assign \o0-63 [59] = \191-255 [2];
  assign \o0-63 [60] = \191-255 [14];
  assign \o0-63 [61] = \191-255 [26];
  assign \o0-63 [62] = \191-255 [38];
  assign \o0-63 [63] = \191-255 [50];
  assign \o64-127 [0] = \191-255 [62];
  assign \o64-127 [1] = \0-63 [9];
  assign \o64-127 [2] = \0-63 [21];
  assign \o64-127 [3] = \0-63 [33];
  assign \o64-127 [4] = \0-63 [45];
  assign \o64-127 [5] = \0-63 [57];
  assign \o64-127 [6] = \64-127 [5];
  assign \o64-127 [7] = \64-127 [17];
  assign \o64-127 [8] = \64-127 [29];
  assign \o64-127 [9] = \64-127 [41];
  assign \o64-127 [10] = \64-127 [53];
  assign \o64-127 [11] = \128-191 [1];
  assign \o64-127 [12] = \128-191 [13];
  assign \o64-127 [13] = \128-191 [25];
  assign \o64-127 [14] = \128-191 [37];
  assign \o64-127 [15] = \128-191 [49];
  assign \o64-127 [16] = \128-191 [61];
  assign \o64-127 [17] = \191-255 [9];
  assign \o64-127 [18] = \191-255 [21];
  assign \o64-127 [19] = \191-255 [33];
  assign \o64-127 [20] = \191-255 [45];
  assign \o64-127 [21] = \191-255 [57];
  assign \o64-127 [22] = \0-63 [4];
  assign \o64-127 [23] = \0-63 [16];
  assign \o64-127 [24] = \0-63 [28];
  assign \o64-127 [25] = \0-63 [40];
  assign \o64-127 [26] = \0-63 [52];
  assign \o64-127 [27] = \64-127 [0];
  assign \o64-127 [28] = \64-127 [12];
  assign \o64-127 [29] = \64-127 [24];
  assign \o64-127 [30] = \64-127 [36];
  assign \o64-127 [31] = \64-127 [48];
  assign \o64-127 [32] = \64-127 [60];
  assign \o64-127 [33] = \128-191 [8];
  assign \o64-127 [34] = \128-191 [20];
  assign \o64-127 [35] = \128-191 [32];
  assign \o64-127 [36] = \128-191 [44];
  assign \o64-127 [37] = \128-191 [56];
  assign \o64-127 [38] = \191-255 [4];
  assign \o64-127 [39] = \191-255 [16];
  assign \o64-127 [40] = \191-255 [28];
  assign \o64-127 [41] = \191-255 [40];
  assign \o64-127 [42] = \191-255 [52];
  assign \o64-127 [43] = \256 ;
  assign \o64-127 [44] = \0-63 [11];
  assign \o64-127 [45] = \0-63 [23];
  assign \o64-127 [46] = \0-63 [35];
  assign \o64-127 [47] = \0-63 [47];
  assign \o64-127 [48] = \0-63 [59];
  assign \o64-127 [49] = \64-127 [7];
  assign \o64-127 [50] = \64-127 [19];
  assign \o64-127 [51] = \64-127 [31];
  assign \o64-127 [52] = \64-127 [43];
  assign \o64-127 [53] = \64-127 [55];
  assign \o64-127 [54] = \128-191 [3];
  assign \o64-127 [55] = \128-191 [15];
  assign \o64-127 [56] = \128-191 [27];
  assign \o64-127 [57] = \128-191 [39];
  assign \o64-127 [58] = \128-191 [51];
  assign \o64-127 [59] = \128-191 [63];
  assign \o64-127 [60] = \191-255 [11];
  assign \o64-127 [61] = \191-255 [23];
  assign \o64-127 [62] = \191-255 [35];
  assign \o64-127 [63] = \191-255 [47];
  assign \o192-255 [0] = \191-255 [59];
  assign \o192-255 [1] = \0-63 [6];
  assign \o192-255 [2] = \0-63 [18];
  assign \o192-255 [3] = \0-63 [30];
  assign \o192-255 [4] = \0-63 [42];
  assign \o192-255 [5] = \0-63 [54];
  assign \o192-255 [6] = \64-127 [2];
  assign \o192-255 [7] = \64-127 [14];
  assign \o192-255 [8] = \64-127 [26];
  assign \o192-255 [9] = \64-127 [38];
  assign \o192-255 [10] = \64-127 [50];
  assign \o192-255 [11] = \64-127 [62];
  assign \o192-255 [12] = \128-191 [10];
  assign \o192-255 [13] = \128-191 [22];
  assign \o192-255 [14] = \128-191 [34];
  assign \o192-255 [15] = \128-191 [46];
  assign \o192-255 [16] = \128-191 [58];
  assign \o192-255 [17] = \191-255 [6];
  assign \o192-255 [18] = \191-255 [18];
  assign \o192-255 [19] = \191-255 [30];
  assign \o192-255 [20] = \191-255 [42];
  assign \o192-255 [21] = \191-255 [54];
  assign \o192-255 [22] = \0-63 [1];
  assign \o192-255 [23] = \0-63 [13];
  assign \o192-255 [24] = \0-63 [25];
  assign \o192-255 [25] = \0-63 [37];
  assign \o192-255 [26] = \0-63 [49];
  assign \o192-255 [27] = \0-63 [61];
  assign \o192-255 [28] = \64-127 [9];
  assign \o192-255 [29] = \64-127 [21];
  assign \o192-255 [30] = \64-127 [33];
  assign \o192-255 [31] = \64-127 [45];
  assign \o192-255 [32] = \64-127 [57];
  assign \o192-255 [33] = \128-191 [5];
  assign \o192-255 [34] = \128-191 [17];
  assign \o192-255 [35] = \128-191 [29];
  assign \o192-255 [36] = \128-191 [41];
  assign \o192-255 [37] = \128-191 [53];
  assign \o192-255 [38] = \191-255 [1];
  assign \o192-255 [39] = \191-255 [13];
  assign \o192-255 [40] = \191-255 [25];
  assign \o192-255 [41] = \191-255 [37];
  assign \o192-255 [42] = \191-255 [49];
  assign \o192-255 [43] = \191-255 [61];
  assign \o192-255 [44] = \0-63 [8];
  assign \o192-255 [45] = \0-63 [20];
  assign \o192-255 [46] = \0-63 [32];
  assign \o192-255 [47] = \0-63 [44];
  assign \o192-255 [48] = \0-63 [56];
  assign \o192-255 [49] = \64-127 [4];
  assign \o192-255 [50] = \64-127 [16];
  assign \o192-255 [51] = \64-127 [28];
  assign \o192-255 [52] = \64-127 [40];
  assign \o192-255 [53] = \64-127 [52];
  assign \o192-255 [54] = \128-191 [0];
  assign \o192-255 [55] = \128-191 [12];
  assign \o192-255 [56] = \128-191 [24];
  assign \o192-255 [57] = \128-191 [36];
  assign \o192-255 [58] = \128-191 [48];
  assign \o192-255 [59] = \128-191 [60];
  assign \o192-255 [60] = \191-255 [8];
  assign \o192-255 [61] = \191-255 [20];
  assign \o192-255 [62] = \191-255 [32];
  assign \o192-255 [63] = \191-255 [44];
  assign \o128-191 [0] = \191-255 [56];
  assign \o128-191 [1] = \0-63 [3];
  assign \o128-191 [2] = \0-63 [15];
  assign \o128-191 [3] = \0-63 [27];
  assign \o128-191 [4] = \0-63 [39];
  assign \o128-191 [5] = \0-63 [51];
  assign \o128-191 [6] = \0-63 [63];
  assign \o128-191 [7] = \64-127 [11];
  assign \o128-191 [8] = \64-127 [23];
  assign \o128-191 [9] = \64-127 [35];
  assign \o128-191 [10] = \64-127 [47];
  assign \o128-191 [11] = \64-127 [59];
  assign \o128-191 [12] = \128-191 [7];
  assign \o128-191 [13] = \128-191 [19];
  assign \o128-191 [14] = \128-191 [31];
  assign \o128-191 [15] = \128-191 [43];
  assign \o128-191 [16] = \128-191 [55];
  assign \o128-191 [17] = \191-255 [3];
  assign \o128-191 [18] = \191-255 [15];
  assign \o128-191 [19] = \191-255 [27];
  assign \o128-191 [20] = \191-255 [39];
  assign \o128-191 [21] = \191-255 [51];
  assign \o128-191 [22] = \191-255 [63];
  assign \o128-191 [23] = \0-63 [10];
  assign \o128-191 [24] = \0-63 [22];
  assign \o128-191 [25] = \0-63 [34];
  assign \o128-191 [26] = \0-63 [46];
  assign \o128-191 [27] = \0-63 [58];
  assign \o128-191 [28] = \64-127 [6];
  assign \o128-191 [29] = \64-127 [18];
  assign \o128-191 [30] = \64-127 [30];
  assign \o128-191 [31] = \64-127 [42];
  assign \o128-191 [32] = \64-127 [54];
  assign \o128-191 [33] = \128-191 [2];
  assign \o128-191 [34] = \128-191 [14];
  assign \o128-191 [35] = \128-191 [26];
  assign \o128-191 [36] = \128-191 [38];
  assign \o128-191 [37] = \128-191 [50];
  assign \o128-191 [38] = \128-191 [62];
  assign \o128-191 [39] = \191-255 [10];
  assign \o128-191 [40] = \191-255 [22];
  assign \o128-191 [41] = \191-255 [34];
  assign \o128-191 [42] = \191-255 [46];
  assign \o128-191 [43] = \191-255 [58];
  assign \o128-191 [44] = \0-63 [5];
  assign \o128-191 [45] = \0-63 [17];
  assign \o128-191 [46] = \0-63 [29];
  assign \o128-191 [47] = \0-63 [41];
  assign \o128-191 [48] = \0-63 [53];
  assign \o128-191 [49] = \64-127 [1];
  assign \o128-191 [50] = \64-127 [13];
  assign \o128-191 [51] = \64-127 [25];
  assign \o128-191 [52] = \64-127 [37];
  assign \o128-191 [53] = \64-127 [49];
  assign \o128-191 [54] = \64-127 [61];
  assign \o128-191 [55] = \128-191 [9];
  assign \o128-191 [56] = \128-191 [21];
  assign \o128-191 [57] = \128-191 [33];
  assign \o128-191 [58] = \128-191 [45];
  assign \o128-191 [59] = \128-191 [57];
  assign \o128-191 [60] = \191-255 [5];
  assign \o128-191 [61] = \191-255 [17];
  assign \o128-191 [62] = \191-255 [29];
  assign \o128-191 [63] = \191-255 [41];
  assign o256 = \191-255 [53];
endmodule

module Subterranean_round (
  input [63:0] \0-63 ,
  input [63:0] \64-127 ,
  input [63:0] \128-191 ,
  input [63:0] \192-255 ,
  input \256 ,
  output [63:0] \o0-63 ,
  output [63:0] \o64-127 ,
  output [63:0] \o128-191 ,
  output [63:0] \o191-255 ,
  output o256
);
  wire [63:0] s0;
  wire [63:0] s1;
  wire [63:0] s2;
  wire [63:0] s3;
  wire s4;
  wire [63:0] s5;
  wire [63:0] s6;
  wire [63:0] s7;
  wire [63:0] s8;
  wire s9;
  wire [63:0] s10;
  wire [63:0] s11;
  wire [63:0] s12;
  wire [63:0] s13;
  wire s14;
  \?  \?_i0 (
    .\64-127 ( \0-63  ),
    .\128-191 ( \64-127  ),
    .\191-255 ( \128-191  ),
    .\0-63 ( \192-255  ),
    .\256 ( \256  ),
    .\o0-63 ( s0 ),
    .\o64-127 ( s1 ),
    .\o128-191 ( s2 ),
    .\o192-255 ( s3 ),
    .o256( s4 )
  );
  \?  \?_i1 (
    .\64-127 ( s0 ),
    .\128-191 ( s1 ),
    .\191-255 ( s2 ),
    .\0-63 ( s3 ),
    .\256 ( s4 ),
    .\o0-63 ( s5 ),
    .\o64-127 ( s6 ),
    .\o128-191 ( s7 ),
    .\o192-255 ( s8 ),
    .o256( s9 )
  );
  \?  \?_i2 (
    .\0-63 ( s5 ),
    .\64-127 ( s6 ),
    .\128-191 ( s7 ),
    .\192-255 ( s8 ),
    .\256 ( s9 ),
    .\o0-63 ( s10 ),
    .\o64-127 ( s11 ),
    .\o128-191 ( s12 ),
    .\o192-255 ( s13 ),
    .o256( s14 )
  );
  \?  \?_i3 (
    .\64-127 ( s10 ),
    .\128-191 ( s11 ),
    .\191-255 ( s12 ),
    .\0-63 ( s13 ),
    .\256 ( s14 ),
    .\o0-63 ( \o0-63  ),
    .\o64-127 ( \o64-127  ),
    .\o128-191 ( \o128-191  ),
    .\o192-255 ( \o191-255  ),
    .o256( o256 )
  );
endmodule
