-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

-- ? : si ? si + ?i
-- where ?_i = 1 if i = 0 else 1
entity main is
  port (
    n64_127: in std_logic_vector(63 downto 0);
    n128_191: in std_logic_vector(63 downto 0);
    n191_255: in std_logic_vector(63 downto 0);
    n0_63: in std_logic_vector(63 downto 0);
    n256: in std_logic;
    o0_63: out std_logic_vector(63 downto 0);
    o64_127: out std_logic_vector(63 downto 0);
    o128_191: out std_logic_vector(63 downto 0);
    o192_255: out std_logic_vector(63 downto 0);
    o256: out std_logic);
end main;

architecture Behavioral of main is
begin
  o0_63(0) <= (n0_63(0) XOR '1');
  o0_63(63 downto 1) <= n0_63(63 downto 1);
  o64_127 <= n64_127;
  o128_191 <= n128_191;
  o192_255 <= n191_255;
  o256 <= n256;
end Behavioral;
